# Numpy Continue 

In [9]:
import numpy as np

In [ ]:
np.arange(start,stop,step) # also support fraction 

In [11]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [15]:
m1 = np.arange(1,5).reshape(2,2)

In [17]:
m1.shape

(2, 2)

In [33]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.arange(1,10).reshape(4,3)

ValueError: cannot reshape array of size 9 into shape (4,3)

In [39]:
np.arange(1,10).reshape(2,3)

ValueError: cannot reshape array of size 9 into shape (2,3)

In [43]:
np.arange(1,9).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [59]:
np.arange(1,17).reshape(1,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [75]:
np.arange(1,17).reshape(16,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [63]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
np.arange(1,17).reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [71]:
np.arange(1,17).reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [73]:
np.arange(1,17).reshape(2,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [77]:
np.arange(1,17).reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [91]:
np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [98]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [104]:
np.arange(0,12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [110]:
np.arange(0,12).reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [106]:
np.arange(0,12).reshape(3,3,3)

ValueError: cannot reshape array of size 12 into shape (3,3,3)

In [112]:
np.arange(0,12).reshape(2,3,3) 

ValueError: cannot reshape array of size 12 into shape (2,3,3)

In [ ]:
(1,n) -> n elements

.reshape(a1,a2,a3 ..... an)  

a1*a2*a3*a4 = n

In [121]:
(5,)

(5,)

# Np Zeros and NP Ones

In [133]:
"""shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.

"""

np.zeros((5,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [139]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [147]:
np.ones((4,4),dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [153]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [179]:
"""Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
"""
np.eye(7,M=6)


# rows and column different

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [187]:
# can we set the random range

In [191]:
np.random.random((5,5))*100

array([[85.00991968, 62.2259987 ,  2.67504299, 37.21144368, 30.19624822],
       [98.04168387, 64.0286658 , 28.47504693, 12.96809269, 88.53328421],
       [51.88297744, 57.426785  , 78.83492618, 67.90095841, 90.88315478],
       [28.60810021, 21.41777414, 32.6872532 , 61.19467507, 77.52582731],
       [39.79760841, 25.65922564, 13.22608283, 33.39181538, 57.60771777]])

In [193]:
np.random.random((2,3))

array([[0.46502424, 0.44201258, 0.61934019],
       [0.70933675, 0.83772782, 0.89209932]])

In [195]:
np.random.random((100,3))

array([[0.87822329, 0.53949908, 0.85155177],
       [0.69482746, 0.83142792, 0.35764472],
       [0.95493209, 0.18333108, 0.30683263],
       [0.73030968, 0.42264589, 0.88683726],
       [0.85246035, 0.94003225, 0.29313591],
       [0.59407489, 0.67055359, 0.63935038],
       [0.35784797, 0.71183672, 0.02177738],
       [0.94829979, 0.04480918, 0.7142933 ],
       [0.98780605, 0.80188648, 0.04920934],
       [0.37511774, 0.23350233, 0.33562168],
       [0.18771739, 0.54556936, 0.17409026],
       [0.55887195, 0.38038628, 0.62512441],
       [0.77464706, 0.53981147, 0.03467227],
       [0.31072931, 0.71391716, 0.6621203 ],
       [0.66851895, 0.3868852 , 0.70305956],
       [0.219152  , 0.23404441, 0.33549632],
       [0.87360472, 0.75516579, 0.49338912],
       [0.71381737, 0.29816621, 0.81033816],
       [0.28320849, 0.52964149, 0.18427158],
       [0.67315733, 0.20954758, 0.23619129],
       [0.61150873, 0.44515347, 0.61422243],
       [0.94551044, 0.85293022, 0.28773392],
       [0.

In [197]:
# use of zeros and ones in industry

In [199]:
np.random.

SyntaxError: invalid syntax (393120376.py, line 1)

In [217]:
np.random.randint(1,100,size=(2,2))

array([[86, 44],
       [ 3, 78]])

In [225]:
np.random.randint(5,10,size=(2,2))

array([[7, 5],
       [6, 6]])

In [ ]:
np.linspace

In [238]:
import math
math.factorial(5)

120

In [248]:
ans=1
for i in range(1,6):
    ans = ans*i

In [252]:
ans

120

# np.linspace

In [262]:
'''Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].
'''

'Return evenly spaced numbers over a specified interval.\n\nReturns `num` evenly spaced samples, calculated over the\ninterval [`start`, `stop`].\n'

In [260]:
np.linspace(0,10,num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [272]:
np.linspace(0,10,num=4).shape

(4,)

In [277]:
import datetime
datetime.datetime.now()

datetime.datetime(2024, 6, 30, 11, 32, 22, 558352)

In [281]:
# on break till 11:40

# Array Attributes

In [288]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [292]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [296]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [298]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [306]:
a1.shape,a2.shape,a3.shape

((10,), (3, 4), (2, 2, 2))

In [310]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [319]:
a1.size,a2.size,a3.size # No of elements in the array

(10, 12, 8)

In [325]:
a1.itemsize # return capacity of every element in an array in Bytes


8 bit = 1 byte 
int32 means 32 bit = 4 byte

4

In [329]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int64'))

In [338]:
a4 = np.array([1,2.5])
a4

array([1. , 2.5])

In [336]:
a4[0].dtype,a4[1].dtype

(dtype('float64'), dtype('float64'))

In [ ]:
int,float

str

In [342]:
a5=np.array([1,'python'])

In [349]:
a5[0].dtype,a5[1].dtype

(dtype('<U1'), dtype('<U6'))

# As type

In [355]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [373]:
a1 = a1.astype(str)

In [359]:
a1 = a1.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [361]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [363]:
s = "mayank"


In [367]:
s.split('a')

['m', 'y', 'nk']

In [377]:
s

'mayank'

In [382]:
a1

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U11')

In [386]:
a1.astype(np.float_)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Array Operation

In [395]:
a1 = np.arange(1,10)

In [405]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [407]:
a1[0],a1[9] 

0 -> 1
9 -> error

SyntaxError: invalid syntax (447672172.py, line 3)

In [411]:
a1[0:4]

array([1, 2, 3, 4])

In [413]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [455]:
a2[-1]

array([ 8.,  9., 10., 11.])

In [417]:
a2.shape

(3, 4)

In [419]:
a2[0:2,0:2]

array([[0., 1.],
       [4., 5.]])

In [427]:
a2[0][2]

2.0

In [437]:
l1 = [[1,2,3 ] , 4 ,5]



In [445]:
a2[1][0:3][-1]

6.0

In [449]:
a1[-9:-6]

array([1, 2, 3])

# Arithematic operation

In [466]:
a1 = np.arange(1,3)

In [468]:
a1/10

array([0.1, 0.2])

In [472]:
a1*10

array([10, 20])

In [474]:
a1

array([1, 2])

In [476]:
a1 + 5

array([6, 7])

In [478]:
a1-5

array([-4, -3])

In [ ]:
+,-,*,/,//,%


In [480]:
a1

array([1, 2])

In [486]:
a6 = np.arange(1,6)
a6

array([1, 2, 3, 4, 5])

In [488]:
a6>3

array([False, False, False,  True,  True])

In [506]:
a6!=3

array([ True,  True, False,  True,  True])

In [508]:
a6>3

array([False, False, False,  True,  True])

In [504]:
a6

array([1, 2, 3, 4, 5])

In [512]:
a6[ a6>2 ]

array([3, 4, 5])

In [516]:
a6

array([1, 2, 3, 4, 5])

In [518]:
a6 [ a6  > 4]

array([5])

In [522]:
a6 [ [ True,False,False,False,False]   ]

array([1])

In [526]:
a6>4

array([False, False, False, False,  True])

In [560]:
a6[ [False, False, False, False,  True] ] = a6 [a6>4]

ValueError: NumPy boolean array indexing assignment cannot assign 5 input values to the 1 output values where the mask is true

In [534]:
a6[a6>4]

array([5])

In [538]:
a6>5

array([False, False, False, False, False])

In [540]:
How to return the index of the elements for a6 [a6>3]?

SyntaxError: invalid syntax (1191208096.py, line 1)

In [546]:
a6 = a6*10
a6

array([10, 20, 30, 40, 50])

In [548]:
np.where(a6>30)

(array([3, 4]),)

In [558]:
a6<35

array([ True,  True,  True, False, False])

In [562]:
a6[ a6 < 35 ] 

array([10, 20, 30])

In [575]:
a6 < 35

array([ True,  True,  True, False, False])

In [577]:
a1

array([1, 2])

In [ ]:
a6 > 30

In [585]:
a1 

array([1, 2])

In [587]:
a1 = np.arange(0,4).reshape(2,2)

In [589]:
a1

array([[0, 1],
       [2, 3]])

In [597]:
np.max
np.min,
np.prod
np.mean
np.median
np.sin
np.cos
np.divide

3

In [ ]:
# 0 for column 
# 1 for row

In [601]:
np.max(a1,axis=1)

array([1, 3])

In [603]:
np.max(a1,axis=0)

array([2, 3])

In [605]:
np.min(a1,axis=0)

array([0, 1])

In [609]:
np.prod(a1)

0

In [612]:
a1

array([[0, 1],
       [2, 3]])

In [614]:
np.mean(a1) # 0 + 1 + 2 + 3  = 6   6 /4 = 

1.5

In [618]:
np.mean(a1,axis=1)

array([0.5, 2.5])

In [620]:
np.sin(a1)

array([[0.        , 0.84147098],
       [0.90929743, 0.14112001]])

# iterate on an array

In [627]:
l1 = [1,2,3]
l2 = [l1,l1,l1]
l3 = [l2,l2,l2]

In [631]:
l1

[1, 2, 3]

In [635]:
l2

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [647]:
l2[0]

[1, 2, 3]

In [639]:
l3

[[[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
 [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]

In [653]:
for elem in l2:
    for nestedElem in elem:
        print (nestedElem)

1
2
3
1
2
3
1
2
3


In [657]:
for elem in l3:
    for nestedElem in elem:
        print (nestedElem)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


In [659]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [661]:
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [669]:
for i in a3:
    print("This line -> " ,i)

This line ->  [[0 1]
 [2 3]]
This line ->  [[4 5]
 [6 7]]


In [678]:
for i in np.ravel(a3): 
    print("This line -> " ,i)

This line ->  0
This line ->  1
This line ->  2
This line ->  3
This line ->  4
This line ->  5
This line ->  6
This line ->  7


In [680]:
for i in np.nditer(a3):
    print("This line -> " ,i)

This line ->  0
This line ->  1
This line ->  2
This line ->  3
This line ->  4
This line ->  5
This line ->  6
This line ->  7




print("Let us push the code to git")