# NumPy Library Overview

This notebook provides a comprehensive overview of the NumPy library, covering array creation, attributes, operations, and broadcasting.

## 1. Creating NumPy Arrays

In [8]:
import numpy as np

# Create arrays with different methods
array_from_list = np.array([1, 2, 3, 4, 5])
array_with_type = np.array([1, 2, 3, 4, 5], dtype='float32')
array_using_arange = np.arange(0, 10, 2)
array_of_ones = np.ones((3, 3))
array_of_zeros = np.zeros((2, 2))
identity_matrix = np.eye(3)
random_array = np.random.random((3, 3))
linspace_array = np.linspace(0, 10, 5)

array_from_list, array_with_type, array_using_arange, array_of_ones, array_of_zeros, identity_matrix, random_array, linspace_array

(array([1, 2, 3, 4, 5]),
 array([1., 2., 3., 4., 5.], dtype=float32),
 array([0, 2, 4, 6, 8]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[0.58943285, 0.51794938, 0.7713326 ],
        [0.28716377, 0.03246446, 0.41550428],
        [0.02798523, 0.90959525, 0.79242667]]),
 array([ 0. ,  2.5,  5. ,  7.5, 10. ]))

## 2. Array Attributes

In [2]:
# Example array
example_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Array attributes
shape = example_array.shape
dtype = example_array.dtype
itemsize = example_array.itemsize
size = example_array.size

shape, dtype, itemsize, size

## 3. Array Operations

In [3]:
# Slicing and Indexing
sliced_array = example_array[1:, 1:]

# Scalar operations
added_array = example_array + 10
multiplied_array = example_array * 2

# Element-wise operations
added_arrays = example_array + example_array
multiplied_arrays = example_array * example_array

sliced_array, added_array, multiplied_array, added_arrays, multiplied_arrays

## 4. Broadcasting

In [4]:
# Broadcasting example
array_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_b = np.array([1, 0, 1])

broadcasted_sum = array_a + array_b
broadcasted_sum

## 5. Dot Product

In [5]:
# Dot product example
array_c = np.array([[1, 2], [3, 4]])
array_d = np.array([[5, 6], [7, 8]])

dot_product = np.dot(array_c, array_d)
dot_product

## 6. More Examples and Exercises

### Example 1: Element-wise comparison

In [6]:
# Element-wise comparison example
array_e = np.array([1, 2, 3])
array_f = np.array([3, 2, 1])

comparison = array_e > array_f
comparison

### Example 2: Summing elements

In [7]:
# Summing elements example
sum_elements = np.sum(example_array)
sum_elements

### Example 3: Reshaping arrays

In [8]:
# Reshaping example
reshaped_array = example_array.reshape((1, 9))
reshaped_array

### Example 4: Stacking arrays

In [9]:
# Stacking example
array_g = np.array([1, 2, 3])
array_h = np.array([4, 5, 6])

stacked_array = np.vstack((array_g, array_h))
stacked_array

### Example 5: Splitting arrays

In [10]:
# Splitting example
array_i = np.array([1, 2, 3, 4, 5, 6])

split_array = np.split(array_i, 3)
split_array