In [4]:
import numpy as np   #alias

In [6]:
l1 = [1,2,3]

In [8]:
l2 = [l1,l1]

In [10]:
l1

[1, 2, 3]

In [14]:
l2

[[1, 2, 3], [1, 2, 3]]

In [30]:
l3 = [1,"abc",1.5] #heterogenous


type(l3[0])

int

In [38]:
n1 = np.array((1,2,3.5))

type(n1[2])


numpy.float64

In [50]:
n1 = np.array(('1',2,3.5))

In [48]:
type(n1[0])
n1

array(['1', '2', '3.5'], dtype='<U32')

In [ ]:
np.array

# Creating Numpy arrays

In [54]:
l1

[1, 2, 3]

In [56]:
# 0D

In [70]:
n0 = np.array(3)
n0,n0.ndim

(array(3), 0)

In [72]:
n1 = np.array([1,2,3])
n1,n1.ndim

(array([1, 2, 3]), 1)

In [76]:
n2 = np.array( [ [1,2,3] , [4,5,6] ]   )
n2 , n2.ndim

(array([[1, 2, 3],
        [4, 5, 6]]),
 2)

In [84]:
n3 = np.array( [ [[ 1,2,3],[4,5,6]]   , [[1,2,3] ])
n3,n3.ndim

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (1643454393.py, line 1)

In [82]:
n4 = np.array([n3,n3])

n4,n4.ndim

(array([[[[1, 2, 3],
          [4, 5, 6]],
 
         [[1, 2, 3],
          [4, 5, 6]]],
 
 
        [[[1, 2, 3],
          [4, 5, 6]],
 
         [[1, 2, 3],
          [4, 5, 6]]]]),
 4)

# We can create a numpy arrays with Sequence/Iterable or an array like object.

# How to specifiy the type of our resultant array.

In [113]:
np.array([1,2,3],dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [117]:
np.array(['1',2,3],dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [121]:
np.array(['mayank',2,3],dtype=np.int32)

ValueError: invalid literal for int() with base 10: 'mayank'

In [126]:
n1 = np.array((1,2,3,),dtype=str)

In [128]:
type(n1)

numpy.ndarray

In [133]:
n1

array(['1', '2', '3'], dtype='<U1')

In [138]:
list(range(0,4))

[0, 1, 2, 3]

In [140]:
list(range(0,4,2))

[0, 2]

In [142]:
np.array(list(range(1,10)))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
np.arange(0,-3,-1)

array([ 0, -1, -2])

In [155]:
list(range(0,4,1.5))

TypeError: 'float' object cannot be interpreted as an integer

In [165]:
np.arange(0,3.01,1.5)

array([0. , 1.5, 3. ])

In [ ]:
list(range(1))

In [171]:
np.arange(0,0.4,0.1,dtype = float)

array([0. , 0.1, 0.2, 0.3])

In [173]:
np.arange(0.,3.5,1.9) 

array([0. , 1.9])