# Numpy Cont

# Matrix Operation

In [11]:
import numpy as np

In [15]:

a1 = np.arange(1,7).reshape(2,3)


In [19]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a2 = np.arange(7,13).reshape(3,2)

In [27]:
a2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [36]:
np.dot(a1,a2)

array([[ 58,  64],
       [139, 154]])

In [40]:
a3 = np.arange(7,13).reshape(1,6)

In [42]:
np.dot(a1,a3)

ValueError: shapes (2,3) and (1,6) not aligned: 3 (dim 1) != 1 (dim 0)

# Normal Numpy Array Operation

In [50]:

a5 = np.arange(1,7).reshape(2,3)
a6 = np.arange(11,17).reshape(2,3)


In [54]:
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a6

array([[11, 12, 13],
       [14, 15, 16]])

In [62]:
a5+a6

array([[12, 14, 16],
       [18, 20, 22]])

In [66]:
a5-a6

array([[-10, -10, -10],
       [-10, -10, -10]])

In [68]:
a5*a6

array([[11, 24, 39],
       [56, 75, 96]])

# Broadcasting

In [77]:
a9 = np.arange(1,11).reshape(5,2)

a9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
a10 = np.arange(1,4).reshape(3,1)
a10

array([[1],
       [2],
       [3]])

In [83]:
a9 + a10

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [90]:
a11 = np.arange(1,11).reshape(5,2)

a11

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [94]:
a11 + a10

ValueError: operands could not be broadcast together with shapes (5,2) (3,1) 

In [115]:
a12= np.arange(0,9).reshape(3,3)

In [123]:
a13 = np.arange(0,3).reshape(3,1)

In [117]:
a12

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
a13

array([[0, 1, 2]])

In [125]:
a12 + a13

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [130]:
b1 = np.array([1,2,3])
b1,b1.shape

(array([1, 2, 3]), (3,))

In [141]:
b1 + 5

array([6, 7, 8])

In [153]:
a11 + np.array([1,2,3,4,5]).reshape(5,1)

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12],
       [14, 15]])